#!/usr/bin/perl
#
# This code is distributed under the terms of the GPL
#
# (c) 2013,2014 umberto.m http://joeyramone76.altervista.org/ipcop
#
# $Id: install-updxlrlog,v 1.0.0 2014/03/07 00:00:00 umberto.m Exp $

$scriptpath=substr($0,0,rindex($0,"/"));

system("$scriptpath/install.sh -i");

