%tr = (%tr,
'updxlrlog log' => 'UpdateAccelerator Cache Logs',
'updxlrlog download log' => 'UpdateAccelerator Download Logs',
'updxlrlog options' => 'updxlrlog Options',
'updxlrlog response code' => 'Response Code',
'updxlrlog enable match criteria' => 'Enable Match Criteria',
'updxlrlog match criteria' => 'Match Criteria',
'updxlrlog sort by' => 'Sort by',
'updxlrlog sort by date' => 'Date',
'updxlrlog sort by result code' => 'Response code',
'updxlrlog sort by duration' => 'Duration',
'updxlrlog sort by duration and size' => 'Duration and Size',
'updxlrlog sort by size' => 'Size',
'updxlrlog sort by url' => 'URL',
'updxlrlog order asc' => 'ASC',
'updxlrlog order desc' => 'DESC',
'updxlrlog order' => 'Order',
'updxlrlog truncate url' => 'Truncate Url',
'updxlrlog full url' => 'Full Url',
'updxlrlog measures raw' => 'No Format for Size, Speed and Duration column',
'updxlrlog duration in sec' => 'Duration (in sec)',
'updxlrlog duration in ms' => 'Duration (in ms)',
'updxlrlog duration' => 'Duration',
'updxlrlog size in hr' => 'Size',
'updxlrlog size in bytes' => 'Size (in bytes)',
'updxlrlog transfer rate speed' => 'Transfer Rate',
'updxlrlog sorting options' => 'Sorting Options',
'updxlrlog request method' => 'Request Method',
'updxlrlog update notification' => 'Update notification!',
'updxlrlog update information' => 'There is an updated version available for download. Visit <a href="http://joeyramone76.altervista.org/updxlrlog" target="_blank">http://joeyramone76.altervista.org/updxlrlog</a> for more information.',
'updxlrlog current installed version' => 'Current Installed Version',
'updxlrlog prev' => 'Previous',
'updxlrlog next' => 'Next',
);

