%tr = (%tr,
'updxlrlog proxy log' => 'Update Accelerator Proxy Logs',
'updxlrlog options' => 'Opzioni Log',
'updxlrlog response code' => 'Codice Risposta',
'updxlrlog enable match criteria' => 'Abilita Criteri Corrispondenza',
'updxlrlog match criteria' => 'Criteri Corrispondenza',
'updxlrlog sort by' => 'Ordina per',
'updxlrlog sort by date' => 'Data',
'updxlrlog sort by result code' => 'Codice Risposta',
'updxlrlog sort by duration' => 'Durata',
'updxlrlog sort by duration and size' => 'Durata e Grandezza',
'updxlrlog sort by size' => 'Grandezza',
'updxlrlog sort by url' => 'URL',
'updxlrlog order asc' => 'ASC',
'updxlrlog order desc' => 'DISC',
'updxlrlog order' => 'Ordine',
'updxlrlog truncate url' => 'Tronca Url',
'updxlrlog full url' => 'Url Completo',
'updxlrlog measures raw' => 'Non formattare le colonne Grandezza, Velocità e Durata',
'updxlrlog duration in sec' => 'Durata (in sec)',
'updxlrlog duration in ms' => 'Durata (in ms)',
'updxlrlog duration' => 'Durata',
'updxlrlog size in hr' => 'Grandezza',
'updxlrlog size in bytes' => 'Grandezza (in bytes)',
'updxlrlog transfer rate speed' => 'Velocità Trasferimento',
'updxlrlog sorting options' => 'Opzioni Ordinamento',
'updxlrlog request method' => 'Metodo Richiesta',
'updxlrlog update notification' => 'UpdxlrLog - Aggiornamenti Disponibili!',
'updxlrlog update information' => 'Disponibile un nuovo aggiornamento per UpdxlrLog. Visita <a href="http://joeyramone76.altervista.org/updxlrlog" target="_blank">http://joeyramone76.altervista.org/updxlrlog</a> per informazioni e download.',
'updxlrlog current installed version' => 'Versione attualmente installata',
'updxlrlog prev' => 'Precedente',
'updxlrlog next' => 'Successiva',
);

